name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"          
      - "app/**"          
      - "Dockerfile"     
      - "run.py"     
      - "requirements.txt"      
         
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"          
      - "app/**"         
      - "Dockerfile"      
      - "run.py"      
      - "requirements.txt"      
       
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit

    - name: Run Flake8 (lint)
      run: flake8 .

    - name: Run Bandit (security scan)
      run: bandit -r .
    - name: Trivy FS scan
      uses: aquasecurity/trivy-action@0.14.0
      with:
        scan-type: fs
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        path: .



  build-and-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy Image scan
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Push Docker image
        if: success()
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest


  update-helm-values:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v4
        with:
          repository: muhab404/helm-python-app
          token: ${{ secrets.GH_PAT }}  
          ref: main

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update values.yaml with new image tag
        run: |
          echo "Updating values.yaml with tag: $SHORT_SHA"
          sed -i "s|tag:.*|tag: ${SHORT_SHA}|" values.yaml
          cat values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add values.yaml
          git commit -m "Update image tag to ${SHORT_SHA}"
          git push origin main

#   push-to-ecr:
#     runs-on: ubuntu-latest
#     needs: build-and-scan
#     steps:
#       - uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
#       - uses: aws-actions/amazon-ecr-login@v2
#       - run: |
#           IMAGE=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
#           docker tag python-app:${{ github.sha }} $IMAGE
#           docker push $IMAGE